import { EddsaSignature, ExtractedJSONSignature } from "./types";
import { buildPoseidon } from "circomlibjs";
import { Ascii, MAX_JSON_LENGTH, padJSONString } from "./json";
import * as ed from "@noble/ed25519";

const buildEddsa = require("circomlibjs").buildEddsa;
const buildBabyjub = require("circomlibjs").buildBabyjub;

let eddsa;
let babyJub;

function buffer2bits(buff: any) {
    const res = [];
    for (let i = 0; i < buff.length; i++) {
        for (let j = 0; j < 8; j++) {
            if ((buff[i] >> j) & 1) {
                res.push(BigInt(1));
            } else {
                res.push(BigInt(0));
            }
        }
    }
    return res;
}

export async function calculatePoseidon(json: Ascii[]): Promise<string> {
    const poseidon = await buildPoseidon();

    let poseidonRes = poseidon(json.slice(0, 16));
    let i = 16;
    while (i < json.length) {
        poseidonRes = poseidon([poseidonRes].concat(json.slice(i, i + 15)));
        i += 15;
    }
    return poseidon.F.toObject(poseidonRes).toString();
}

const convertDictToBuffer = (dict: Record<string, number>): Uint8Array => {
    const arr = [];
    for (let i = 0; i < Object.keys(dict).length; i++) {
        arr.push(dict[`${i}`]);
    }
    return new Uint8Array(arr);
};

export const finalizeCircuitInputs = (obj: any, jsonText: string) => {};

export const extractPartsFromSignature = (pSignature: Uint8Array, msg: Uint8Array, pubKey: Uint8Array) => {
    const r8Bits = buffer2bits(pSignature.slice(0, 32));
    const sBits = buffer2bits(pSignature.slice(32, 64));
    const aBits = buffer2bits(pubKey);

    return {
        pubKey: aBits.map((el) => el.toString()),
        R8: r8Bits.map((el) => el.toString()),
        S: sBits.map((el) => el.toString()),
    };
};

//extracts the signature and the json from a trusted API that signs requests
export const extractSignatureInputs = (input: string): ExtractedJSONSignature => {
    const jsonSignature = JSON.parse(input);
    const packedSignature = convertDictToBuffer(jsonSignature.signature);
    const servicePubkey = convertDictToBuffer(jsonSignature.servicePubkey);
    const newFormattedJSON = padJSONString(JSON.stringify(jsonSignature.json), MAX_JSON_LENGTH);
    return { packedSignature, servicePubkey, jsonText: jsonSignature.json, formattedJSON: newFormattedJSON };
};

export const generateEddsaSignature = async (privateKey: Uint8Array, msg: Uint8Array): Promise<EddsaSignature> => {
    eddsa = await buildEddsa();
    babyJub = await buildBabyjub();

    const pubKey = eddsa.prv2pub(privateKey);

    const pPubKey = babyJub.packPoint(pubKey);

    const signature = eddsa.signPedersen(privateKey, msg);

    const pSignature = eddsa.packSignature(signature);

    return extractPartsFromSignature(pSignature, msg, pPubKey);
};

export const strHashToBuffer = (hash: string) => {
    let hashValue = BigInt(hash);
    let hashArr = [];
    for (let i = 0; i < 32; i++) {
        hashArr.push(Number(hashValue % BigInt(256)));
        hashValue = hashValue / BigInt(256);
    }
    return Uint8Array.from(hashArr);
};

export const hardCodedInput = {
    hashJsonProgram: BigInt(10058416048496861476264053793475873949645935904167570960039020625334949516197).toString(),
    jsonProgram: [
        123, 34, 110, 97, 109, 101, 34, 58, 34, 102, 111, 111, 98, 97, 114, 34, 44, 34, 118, 97, 108, 117, 101, 34, 58,
        49, 50, 51, 44, 34, 109, 97, 112, 34, 58, 123, 34, 97, 34, 58, 116, 114, 117, 101, 125, 125, 0, 0, 0, 0,
    ].map((el) => el.toString()),
    keys: [
        [
            [34, 109, 97, 112, 34, 0, 0, 0, 0, 0].map((el) => el.toString()),
            [34, 97, 34, 0, 0, 0, 0, 0, 0, 0].map((el) => el.toString()),
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0].map((el) => el.toString()),
        ],
    ],
    values: [[116, 114, 117, 101, 0, 0, 0, 0, 0, 0].map((el) => el.toString())],
    keysOffset: [
        [[29, 33].map((el) => el.toString()), [36, 38].map((el) => el.toString()), [0, 0].map((el) => el.toString())],
    ],
    valuesOffset: [[40, 43].map((el) => el.toString())],
    pubKey: [
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
    ].map((el) => BigInt(el).toString()),
    R8: [
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
    ].map((el) => BigInt(el).toString()),
    S: [
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "1",
        "0",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "1",
        "1",
        "1",
        "0",
        "1",
        "1",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "0",
        "1",
        "0",
        "0",
        "0",
        "0",
        "1",
        "1",
        "1",
        "0",
        "1",
        "0",
        "0",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "1",
        "1",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
    ].map((el) => BigInt(el).toString()),
};
