import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Textarea } from "../components/textarea";
import { useEffect, useMemo, useState } from "react";
import { Button } from "../components/button";
import localforage from "localforage";
import * as ed from "@noble/ed25519";
import * as ethers from "ethers";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [jsonText, setJsonText] = useState<string>("");
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [hasKeypair, setHasKeypair] = useState<boolean>(false);

    useEffect(() => {
        async function checkIsRegistered() {
            const maybePrivKey = await localforage.getItem("zkattestorPrivKey");
            const maybePubKey = await localforage.getItem("zkattestorPubKey");
            if (maybePrivKey && maybePubKey) {
                setHasKeypair(true);
            } else {
                setIsLoading(true);
                const privKey = ed.utils.randomPrivateKey();
                const publicKey = await ed.getPublicKey(privKey);
                await localforage.setItem("zkattestorPrivKey", privKey);
                await localforage.setItem("zkattestorPubKey", publicKey);
                setIsLoading(false);
            }
        }
        checkIsRegistered();
    }, []);

    const signJSON = async () => {
        const privateKey = await localforage.getItem("zkattestorPrivKey");
        const formattedJSON = JSON.stringify(JSON.parse(jsonText));
        const signature = await ed.sign(ethers.utils.toUtf8Bytes(formattedJSON), privateKey as string);
        console.log(signature);
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.center}>
                    <h1 className="py-4">zkAttestor</h1>
                </div>

                {!hasKeypair ? (
                    "generating your key pair..."
                ) : (
                    <div className="w-full flex flex-col items-center justify-center">
                        <Textarea
                            placeholder={"Paste your JSON string"}
                            value={jsonText}
                            onChangeHandler={setJsonText}
                        />
                        <div className="py-4"></div>
                        <Button backgroundColor="black" color="white" onClickHandler={signJSON}>
                            {isLoading ? "loading..." : "Sign JSON"}
                        </Button>
                    </div>
                )}
            </main>
        </>
    );
}
